### ISSUE TITLE
cookbook installs outdated version

### ISSUE THREAD

**Issue by akuzminsky** [chef-cookbooks/etcd#62]
### Cookbook version
3.2.5
### Chef-client version
```
# etcdctl -v
etcdctl version 2.2.2
```
### Platform Details
```
# cat /etc/*-release
CentOS Linux release 7.2.1511 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core)
CentOS Linux release 7.2.1511 (Core)
```
### Scenario:
I'm installing an etcd cluster with DNS discovery.
Due to a bug in 2.2.2 `etcdctl` connects to wrong port.

### Steps to Reproduce:
See discussion on https://groups.google.com/forum/?pli=1#!topic/etcd-dev/R4x9l7pi6fc

### Expected Result:
etcdctl is updated to 2.3.7
### Actual Result:
etcdctl version 2.2.2

**Comment by tas50** [comment]
Cookbook version 4.0 now install 2.3.7. The resource also allows you to install any version you want so you don't need to necessarily bring in the latest release of the cookbook in order to install a newer version of etcd. Check out the usage details in the readme.
