### ISSUE TITLE
init script should not fail when one node starts

### ISSUE THREAD

**Issue by akuzminsky** [chef-cookbooks/etcd#63]
I'm working on etcd cluster with DNS discovery. It's a cluster of three nodes.
According to etcd developers DNS must be ready when first node starts. (See https://github.com/coreos/etcd/issues/5909 for context).

When there are three nodes in DNS and the first node starts it expects quorum. However nodes are starting one by one and second doesn't start until first successfully starts.
Even though etcd starts as expected and behaves as expected in this situation the init script exits with non-zero it breaks `knife bootstrap`.

The init script should exit with zero so second node can start and the cluster becomes operational.

Otherwise it's not possible to start the cluster. Chef will panic on a non-zero code.
The only workaround I see is to start three nodes in parallel which is not appropriate/possible in some cases.

**Comment by tas50** [comment]
@akuzminsky I get the overall problem, but I'm confused on exactly how the startup fails.  Does etcd go into a waiting state while it waits for quorum? Is that just causing the init script to timeout and exit non-zero? It sounds like we need to update the script, but I want to make sure we don't break exit codes from legitimate failures.

**Comment by akuzminsky** [comment]
The init script waits until there is a quorum which is not possible at the moment the first node starts.
After timeout the script exits with non-zero that halts the recipe.

I understand it was implemented this way to make sure the service is available when the script exits, but in this case no quorum is a legit situation.

**Comment by akuzminsky** [comment]
so far I start three nodes simultaneously to workaround the problem, but this is not a good solution

**Comment by tas50** [comment]
I'm thinking at this point we need to rip the code out that checks the health on start because it makes it nearly impossible to setup a real cluster.

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by tas50** [comment]
So I have a potentially solution here in this PR. It's not the best solution, but from all the googling I've done there really isn't a solution. There isn't a "first run" sort of keep going mode in etcd. It just loops forever doing elections.

https://github.com/chef-cookbooks/etcd/pull/79
