### ISSUE TITLE
update docker service manager to install etcd v3

### ISSUE THREAD

**Issue by drywheat** [chef-cookbooks/etcd#69]
#### Cookbook version (4.1.0), Chef-client version (12.15.19)

The `etcd_service_manager_docker` resource maps ports **2379** and **4001** by default. Etcd v3 now uses port **2380** for peer traffic. The `version` and `port` properties should both be updated so that we can use the latest version of etcd by default.

[Here is the port mapping](https://github.com/chef-cookbooks/etcd/blob/v4.1.0/libraries/etcd_service_manager_docker.rb#L9)

**Comment by tas50** [comment]
This has been merged to master.
