### ISSUE TITLE
docker service manager does NOT map host volume

### ISSUE THREAD

**Issue by drywheat** [chef-cookbooks/etcd#70]
#### Cookbook version (4.1.0), Chef-client version (12.15.19)

`etcd_service_manager_docker` does not provide an option to map the `data_dir` to a local volume on the host. Doing so will allow users to restart/update their containers without blasting all of their etcd data, and this is very important in order to maintain cluster stability in production.

**Comment by tas50** [comment]
This is really something we should do. I'll take a look at

**Comment by tas50** [comment]
This has been added to master. I'll get it released today
