### ISSUE TITLE
etcd_service_manager_docker: undefined method new_resource

### ISSUE THREAD

**Issue by lukassup** [chef-cookbooks/etcd#74]
### Cookbook version

etcd 5.0.0 (latest available in https://supermarket.chef.io)

### Chef-client version

Chef: 12.16.42

### Platform Details

Host

Arch Linux x86_64, latest
linux kernel: 4.12.10
Vagrant 1.9.7
libvirtd (libvirt) 3.7.0
vagrant-libvirt (0.0.40)

Guest

Centos 7
linux kernel: 3.10.0-514.26.2.el7.x86_64
Chef: 12.16.42

### Scenario

When trying to converge my recipe containing:

```ruby
docker_service 'default'

etcd_installation_docker 'default' do
  action :create
end

etcd_service_manager_docker 'default' do
  action :start
end
```

I receive the following exception

```
================================================================================
Error executing action `start` on resource 'etcd_service_manager_docker[default]'
================================================================================

NoMethodError
-------------
undefined method `new_resource' for EtcdCookbook::EtcdServiceManagerDocker

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/etcd/libraries/helpers_service.rb:65:in `etcd_name'
/var/chef/cache/cookbooks/etcd/libraries/etcd_service_manager_docker.rb:10:in `block in <class:EtcdServiceManagerDocker>'
/var/chef/cache/cookbooks/etcd/libraries/etcd_service_manager_docker.rb:15:in `block in <class:EtcdServiceManagerDocker>'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/etcd_node/recipes/service.rb

 13: etcd_service_manager_docker 'default' do
 14:   action :start
 15: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/etcd_node/recipes/service.rb:13:in `from_file'

etcd_service_manager_docker("default") do
  action [:start]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :etcd_service_manager_docker
  cookbook_name "etcd_node"
  recipe_name "service"
end

Platform:
---------
x86_64-linux
```
### Steps to Reproduce

Create a cookbook that depends on `etcd` cookbook version `5.0.0` with the recipe mentioned above and try to do a `kitchen converge`.

### Expected Result:

It should converge without errors and have `etcd` setup to run on `docker`.

### Actual Result:

Fails with the above exception right after pulling the `etcd` image.

**Comment by tas50** [comment]
Fixed by https://github.com/chef-cookbooks/etcd/commit/b5cfa1eb54871140875027932f38251efc035ecb

Thanks for the report
